services:
  - type: web
    name: netflix-recommender-api
    runtime: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
